### ISSUE TITLE
Further Migration and Fixing Plan

### ISSUE THREAD

**Issue by pengyin-shan** [healthyregions/spatial-access#3]
The initial version of the fixed Access app has been deployed at: https://helpful-lollipop-5db1fd.netlify.app/. This app should allow the regular-sized Census Tracts file without advanced metrics to be successfully processed. The backend has been fixed and deployed to our AWS account.

This ticket lists further procedures to migrate the full app and fix more problems in this app. They will be processed in steps:

- [x] healthyregions/spatial-access#11
- [x] healthyregions/spatial-access#12
- [x] healthyregions/spatial-access#13
- [x] healthyregions/spatial-access#14
- [ ] healthyregions/spatial-access#5
- [ ] healthyregions/spatial-access#6
- [x] healthyregions/spatial-access#7
- [x] healthyregions/spatial-access#8
- [x] healthyregions/spatial-access#4
